export const LIGHTWEIGHT_COUNT_EVENT_NAMES = new Set([
  'HTTP2_SESSION_UPDATE_RECV_WINDOW',
  'HTTP2_STREAM_UPDATE_RECV_WINDOW',
  'SSL_SOCKET_BYTES_RECEIVED',
  'SOCKET_BYTES_RECEIVED',
  'HTTP2_SESSION_RECV_DATA',
  'HTTP_TRANSACTION_READ_BODY',
  'URL_REQUEST_JOB_FILTERED_BYTES_READ',
  'SIMPLE_CACHE_ENTRY_WRITE_CALL',
  'SIMPLE_CACHE_ENTRY_WRITE_BEGIN',
  'SIMPLE_CACHE_ENTRY_WRITE_END',
  'SIMPLE_CACHE_ENTRY_WRITE_OPTIMISTIC',
  'COOKIE_INCLUSION_STATUS',
]);

export function isLightweightCountEventName(typeName: string | undefined): boolean {
  return Boolean(typeName && LIGHTWEIGHT_COUNT_EVENT_NAMES.has(typeName));
}
