export {
  WORKBENCH_SPIKE_SCHEMA_VERSION,
  WORKBENCH_SCHEMA_VERSION,
} from './spike/protocol';

export type {
  CapabilityMissingResponse,
  CapabilitiesResultResponse,
  CreateSessionRequest,
  EventDetailResultResponse,
  EvidenceResultResponse,
  QueryEventDetailRequest,
  QueryEvidenceRequest,
  QueryCapabilitiesRequest,
  QueryScreenshotIndexRequest,
  QueryScreenshotRequest,
  QuerySelectionRequest,
  QueryViewportRequest,
  SessionCreatedResponse,
  SessionReleasedResponse,
  ScreenshotResultResponse,
  ScreenshotIndexResultResponse,
  SelectionResultResponse,
  StructuredErrorResponse,
  ViewportResultResponse,
  WorkbenchCapability,
  WorkbenchEventDetailDto,
  WorkbenchProgressResponse,
  WorkbenchQueryErrorCode,
  WorkbenchRequest,
  WorkbenchResponse,
  WorkbenchSessionDescriptor,
  WorkbenchSessionRef,
  WorkbenchSessionState,
  WorkbenchSourceRef,
  WorkbenchTimelineEventDto,
  WorkbenchTruncation,
} from './spike/protocol';
